# k3s-gitops-infra/overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - shared/
  - go-api/
  - worker/
  - redis/
  - mysql/
  - portfolio-ui/

labels:
  - includeSelectors: true
    pairs:
      env: staging
      managed-by: argo-cd
      team: k3s-ghost-ops
      project: portfolio-ecosystem

replicas:
  - name: go-api
    count: 0

  - name: worker
    count: 0

  - name: portfolio-ui
    count: 0

  - name: mysql
    count: 0

  - name: redis
    count: 0
