apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-worker
  template:
    metadata:
      labels:
        app: go-worker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              "until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;",
            ]
      containers:
        - name: go-worker
          image: placeholder
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: api-config
            - configMapRef:
                name: go-worker-base-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
