# k3s-gitops-infra/overlays/staging/worker/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/worker
  - ../shared/configmap.yaml

images:
  - name: placeholder
    newName: ghcr.io/zerodayz7/http-server-worker
    newTag: 8817c1e

patchesStrategicMerge:
  - patch-resources.yaml
  - patch-env.yaml
