---
- name: Konfiguracja AlmaLinux VPS
  hosts: alma
  become: yes

  tasks:
    - name: Instalacja Nginx i narzędzi
      dnf:
        name:
          - nginx
          - git
          - curl
        state: present

    - name: Upewnij się, że Nginx działa i startuje z systemem
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Otwórz porty w Firewallu (HTTP/HTTPS)
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - http
        - https