---
- name: Kompleksowa Reinstalacja AlmaLinux 10
  hosts: alma_vps
  become: yes

  tasks:
    - name: Dodaj zewnętrzne repozytoria (CrowdSec, Tailscale, K3s)
      copy:
        src: "repos/{{ item }}"
        dest: "/etc/yum.repos.d/{{ item }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - crowdsec_crowdsec.repo
        - tailscale.repo
        - rancher-k3s-common.repo

    - name: Konfiguracja Firewall
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 80/tcp
        - 443/tcp
        - 6443/tcp
        - 10250/tcp
        - 1514/tcp
        - 1515/tcp

    - name: Instalacja oprogramowania
      dnf:
        name:
          - git
          - curl
          - crowdsec
          - crowdsec-firewall-bouncer-iptables
          - wazuh-agent
        state: present
        update_cache: yes

    - name: Instalacja Tailscale
      shell: curl -fsSL https://tailscale.com/install.sh | sh
      args:
        creates: /usr/bin/tailscale

    - name: Instalacja K3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ustawienie IP Managera w Wazuh
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: "<address>.*</address>"
        line: "      <address>100.88.179.37</address>"
      notify: Restart Wazuh

  handlers:
    - name: Restart Wazuh
      service:
        name: wazuh-agent
        state: restarted
