apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-worker
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-worker
  template:
    metadata:
      labels:
        app: go-worker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: go-worker
          image: ghcr.io/zerodayz7/http-server-worker:8817c1e
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
            - name: DB_HOST
              value: "mysql"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
            - name: ENV
              value: "staging"
