services:
  # --- MONGO ---
  mongodb:
    image: mongo:7.0-jammy
    container_name: app_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_pass
    secrets:
      - mongo_pass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: app_mongo_express
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
  #     ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ROOT_USER}
  #     ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - app-network

  # --- MYSQL ---
  mysql:
    image: mysql:8
    container_name: app_mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_pass
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    secrets:
      - mysql_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # phpmyadmin:
  #   image: phpmyadmin:5-apache
  #   container_name: app_phpmyadmin
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # --- REDIS ---
  redis:
    image: redis:8.6-alpine
    container_name: app_redis
    secrets:
      - redis_pass
    command: >
      sh -c 'redis-server --requirepass $$(cat /run/secrets/redis_pass)'
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # --- TELEMETRY ---
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:latest
  #   container_name: otel-collector
  #   volumes:
  #     - ./deployments/otel/otel-config.yaml:/etc/otel-col/config.yaml
  #   command: ["--config=/etc/otel-col/config.yaml"]
  #   ports:
  #     - "4317:4317"
  #     - "8889:8889"
  #   networks:
  #     - app-network

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   volumes:
  #     - ./deployments/otel/prometheus.yaml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - app-network

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   container_name: jaeger
  #   ports:
  #     - "16686:16686"
  #     - "4317"
  #   networks:
  #     - app-network

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
  #   networks:
  #     - app-network

secrets:
  mongo_pass:
    file: ./secrets/.mongo_pass
  mysql_pass:
    file: ./secrets/.mysql_pass
  redis_pass:
    file: ./secrets/.redis_pass

volumes:
  mongodb_data:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge
